### ISSUE TITLE
Any directory named `lib` in contracts dir throws error

### ISSUE THREAD

**Issue by brockelmore** [gakonst/dapptools-rs#111]
When you have a structure like this:
```
./
|->lib
|->src
      |-> lib
      |-> my_thing
...
```

The automated remapping tries to treat the `./src/lib` directory as a remapping directory and will likely fail because of that (seen [here](https://github.com/gakonst/dapptools-rs/blob/b5555f910096929125a51e797d85b7a6b6c8bf36/dapptools/src/utils.rs#L85-L98)). I don't know upstream ramifications of a change like this, but it is one option:
```
 /// Gets all the remappings detected
    pub fn find_many(path: &str) -> eyre::Result<Vec<Self>> {
        let path = std::path::Path::new(path);

        if let Ok(paths) = std::fs::read_dir(path) {
            let remappings = paths
                .into_iter()
                // TODO: Surely there must be a better way to convert to str
                .map(|path| Self::find(&path?.path().display().to_string()))
                // Do we want to silently ignore the errors?
                .filter_map(|x| x.ok())
                .collect();
            Ok(remappings)
        } else {
            Ok(vec![])
        }
    }
```

Basically just ignore any errors when remapping fails for a directory. This would likely hide error associated with other remappings?

**Comment by mattsse** [comment]
So the error is really because `path` does not exist and hence `std::fs::read_dir(path)` fails?

I briefly looked at this https://github.com/dapphub/dapptools/blob/b8958a0f01f8f2bde0b489e9793e86e3a8f9a044/src/dapp/libexec/dapp/dapp-remappings, which seems to recursively visit folders and skip those mappings which [do not exist?](https://github.com/dapphub/dapptools/blob/b8958a0f01f8f2bde0b489e9793e86e3a8f9a044/src/dapp/libexec/dapp/dapp-remappings#L22-L25)

**Comment by gakonst** [comment]
This should no longer be the case since https://github.com/gakonst/dapptools-rs/pull/130. Could you please re-run with your same test and re-open if still an issue?
